# Generated by Django 4.2.6 on 2024-03-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=200)),
                ('clientID', models.CharField(max_length=500)),
                ('clientSecret', models.CharField(max_length=200)),
                ('ownerEmail', models.EmailField(max_length=200)),
                ('rollNo', models.IntegerField(max_length=1000)),
            ],
        ),
    ]
